language: c

branches:
  only:
    - master

sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - LLVM_VERSION="3.9.1"
        - LLVM_CONFIG="llvm-config-3.9"
        - config=release
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6

install:
  - bash .travis_install.bash

script:
  - make test
