version: 2
jobs:
  vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps: &ci-steps
      - checkout
      - run: bash .ci-scripts/install-openssl-1.1.0.bash
      - run: make test
      - run: make --directory=examples/hello_world
      - run: make --directory=examples/homie_device
      - run: make --directory=examples/subscribe
      - run: make --directory=examples/tls ssl=1.1.x
  vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps: *ci-steps
  generate-docs:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: make docs
      - persist_to_workspace:
          root: .
          paths:
            - mqtt-docs
  deploy-docs:
    docker:
      - image: python:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: bash .ci-scripts/deploy_docs.bash

workflows:
  version: 2
  commit:
    jobs:
      - vs-ponyc-master
      - vs-ponyc-release
      - generate-docs:
          requires:
            - vs-ponyc-release
          filters:
            branches:
              only: master
      - deploy-docs:
          requires:
            - generate-docs
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - vs-ponyc-master
